apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-elector-deploy 
  labels:
    app: leader-elector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leader-elector
  template:
    metadata:
      labels:
        app: leader-elector
    spec:
      containers:
      - name: le
        image: leader-elector:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 400m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 100Mi