apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-watcher-rb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pod-watcher-sa
    namespace: default
roleRef:
  kind: Role
  name: pod-watcher-role
  apiGroup: rbac.authorization.k8s.io
